### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/dknowledgr#7]
Need to pass tests of the following modules:
- [x] asset
- [x] blockchain
- [ ] broadcast
- [ ] client
- [x] crypto
- [ ] database
- [x] iteratorStream
- [ ] operations
- [ ] rc_api

**Comment by z-th-btc** [comment]
- `client` doesn't pass test
```
2) client
     should make rpc call:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/zhao/work/colab/dknowledgr/test/client.ts)
```

**Comment by z-th-btc** [comment]
- `database api` failure
```
5) database api
     "before all" hook:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/zhao/work/colab/dknowledgr/test/database.ts)
```

**Comment by z-th-btc** [comment]
- `operations` failure
```
6) operations
     "before all" hook:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/zhao/work/colab/dknowledgr/test/operations.ts)
```

**Comment by z-th-btc** [comment]
- `rc_api` failure
```
7) rc_api
     calculateVPMana:
     Error: Invalid asset 'undefined'
      at Function.from (src/steem/asset.ts:89:20)
      at Object.getVests (src/steem/misc.ts:251:40)
      at RCAPI.calculateVPMana (src/helpers/rc.ts:66:34)
      at Context.<anonymous> (test/rc.ts:34:29)
```

**Comment by z-th-btc** [comment]
@oleg-baturov above 7 case failed.
others 55 cases are good.
